/*
 * This source file was generated by the Gradle 'init' task
 */
package sigarka;

import javafx.application.Application;
import javafx.stage.Stage;
import sigarka.scenes.LoginSc;

public class MainApp extends Application {

    @Override
    public void start(Stage stage) {
        stage.setScene(LoginSc.createScene(stage));
        stage.setMaximized(true);
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}